### ISSUE TITLE
Summaries don't work.

### ISSUE THREAD

**Issue by xbony2** [FTB-Gamepedia/MediaWiki-Butt-Ruby#12]
Summaries don't seem to work. Testing [this](https://github.com/xbony2/Experimental-Self-Aware-Electronic-Based-Space-Analyzing-Droid/blob/master/src/main/ruby/xbony2/ircbot/plugins/replaceallincategory.rb) with "@@replaceallincategory Extra Utilities; mod=EXU; mod=EU" with [sample result](http://ftb.gamepedia.com/index.php?title=Blackout_Curtains&diff=218119&oldid=100155&rcid=&curid=13805).

**Comment by elifoster** [comment]
Try doing it without using a hash in your arguments. See elifoster/SatanicBot@36965ae

**Comment by elifoster** [comment]
Okay so this is due to me not understanding splat arguments at the time I wrote it.
