### ISSUE TITLE
Get URL method

### ISSUE THREAD

**Issue by xbony2** [FTB-Gamepedia/MediaWiki-Butt-Ruby#20]
A simple method in Butt getting the wiki's url, like `http://habbo.gamepedia.com` or `http://minecraft-br.gamepedia.com` or whatever.

**Comment by elifoster** [comment]
I'm not sure what API would support this, but I need it as well for watchlist-rb.

**Comment by xbony2** [comment]
Well, we require a URL to be passed to create the butt object, so we can harness that :P

**Comment by elifoster** [comment]
That URL might be completely different than the content URL though.

**Comment by Developaws** [comment]
http://en.wikipedia.org/w/api.php?action=query&meta=siteinfo

result["query"]["general"]["server"]

You're welcome <3

**Comment by Developaws** [comment]
https://github.com/Developaws/PyWikiButt/commit/679312a6f1ab388245bb4a40e32f30411d810d41#diff-89e2164168053f527ffc82c57086cac1

Allows getting the server url, getting the article trailing path, and building the whole url from a page title.
