### ISSUE TITLE
License sucks

### ISSUE THREAD

**Issue by xbony2** [FTB-Gamepedia/MediaWiki-Butt-Ruby#25]
???

**Comment by elifoster** [comment]
As @retep998 pointed out, CC-BY-NC-ND-4.0 sucks in terms of FOSS. We should use a different open source software license. Right now, I'm thinking MIT. What do you think @xbony2 ?

(Side note, the license we choose here will probably be the same for most of my other gems)

**Comment by xbony2** [comment]
The Unlicense?

**Comment by elifoster** [comment]
http://programmers.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense

**Comment by xbony2** [comment]
CC0 1.0 Universal?
