### ISSUE TITLE
Is persistent HTTP connection supported in this library?

### ISSUE THREAD

**Issue by franklinyu** [FTB-Gamepedia/MediaWiki-Butt-Ruby#44]
I think persistent HTTP connection may lower the server burden.

**Comment by elifoster** [comment]
HTTPClient, the HTTP library we use for all of the requests, handles persistent connections. So yeah.

**Comment by franklinyu** [comment]
Great, I read that HTTPClient automatically create and reset connection under the hood.

I am also interested in the [OAuth](https://www.mediawiki.org/wiki/Extension:OAuth) extension. Is it supported?

**Comment by elifoster** [comment]
Currently no extension APIs are supported. This is being worked on at #11 and I'll be sure to include OAuth support when we roll out a version with extension API support. It doesn't seem like OAuth has a very complicated API or change very much.
