### ISSUE TITLE
1.28 MW API changes

### ISSUE THREAD

**Issue by xbony2** [FTB-Gamepedia/MediaWiki-Butt-Ruby#46]
"The following response properties from action=login, deprecated in 1.27, are
  now removed: lgtoken, cookieprefix, sessionid. Clients should handle cookies
  to properly manage session state." - [Early Changelog](https://phabricator.wikimedia.org/diffusion/MW/browse/master/RELEASE-NOTES-1.28). And logging into https://www.mediawiki.org/wiki/ via irb gives a response of "No such action".

**Comment by elifoster** [comment]
We are still on 1.26 at Gamepedia, so we might not want to update until after GP updates to 1.27.

**Comment by xbony2** [comment]
Wikipedia and many other wikis use 1.28. It should be possible to support both versions, even if it's a bit messy.

**Comment by elifoster** [comment]
What do you propose? It would be nice if there was a way to check the version of MW installed on the wiki. If that were a thing, we could even do it in the initializer.

**Comment by xbony2** [comment]
[/w/api.php?action=query&format=json&meta=siteinfo&siprop=general](https://en.wikipedia.org/wiki/Special:ApiSandbox#action=query&format=json&meta=siteinfo&siprop=general).

Or you could put in a simple parameter defaulting to false (use_version_twenty_eight = false).

**Comment by elifoster** [comment]
No that's ugly. The API thing would probably be the best bet, and it would allow us to support versions LTS through latest easily.

**Comment by Developaws** [comment]
https://github.com/Developaws/PyWikiButt/commit/19d32e862f627af00384f0a76b6b6152d45d8529

Has MediaWiki version comparing, and proper lgToken support.
