### ISSUE TITLE
MediaWiki::Utils.encode_url improvements

### ISSUE THREAD

**Issue by xbony2** [FTB-Gamepedia/MediaWiki-Butt-Ruby#81]
See TODO [here](https://github.com/FTB-Gamepedia/MediaWiki-Butt-Ruby/blob/e74c5b75dfa8c9d47ecb41d98f8dad3b38f7e663/lib/mediawiki/utils.rb#L6). Also the documentation could be a bit better. I'm not sure how to import it as a module and it doesn't explain that at all.

**Comment by elifoster** [comment]
That TODO is actually outdated, I didn't fully understand bang! methods at the time. `safely_gsub` was removed from String Utility for this reason in v3.0.0. It does need an improvement however, which is removing all those `or`s. Fair point about documentation; for the time being just know that you call it directly on the utils class, [for example...](https://github.com/FTB-Gamepedia/MediaWiki-Butt-Ruby/blob/e74c5b75dfa8c9d47ecb41d98f8dad3b38f7e663/spec/util_test.rb#L10)
