### ISSUE TITLE
How do I get a category URL? (article URL too)

### ISSUE THREAD

**Issue by Nakilon** [FTB-Gamepedia/MediaWiki-Butt-Ruby#82]
So I get categories as Strings like this:
```ruby
wiki.get_all_categories
```
Now how do I get the URL for a category? Instead of building the "https://..." string manually.

**Comment by elifoster** [comment]
Category URL is not a property for that API action: https://www.mediawiki.org/w/api.php?action=help&modules=query%2Ballcategories

**Comment by Nakilon** [comment]
I didn't ask if it's a property of that API action. Seems like you just don't know the answer. Ok.

**Comment by elifoster** [comment]
You can build the URL accurately using [siteinfo queries](http://ftb-gamepedia.github.io/MediaWiki-Butt-Ruby/MediaWiki/Query/Meta/SiteInfo.html), but there isn't a way to return full URLs directly from query methods that return article names.

**Comment by Nakilon** [comment]
Thank you.
